### ISSUE TITLE
Mac: unable to set break_condition

### ISSUE THREAD

**Issue by kzyapkov** [pyserial/pyserial#103]
On OS X El Capitan (10.11.4), Python 2.7.11 from brew and pyserial 3.0.1 I cannot set the break condition on an FTDI serial adapter: 

```python
>>> import serial
>>> p = serial.Serial('/dev/tty.usbserial-AL017240', 115200)
>>> p.break_condition
False
>>> p.break_condition = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/serial/serialutil.py", line 421, in break_condition
    self._update_break_state()
  File "/usr/local/lib/python2.7/site-packages/serial/serialposix.py", line 591, in _update_break_state
    fcntl.ioctl(self.fd, TIOCSBRK)
IOError: [Errno 25] Inappropriate ioctl for device
```

The same versions work fine on Ubuntu and Arch Linux.

**Comment by zsquareplusc** [comment]
Looks like the driver on OSX does not support BREAK, at least not the variant without a timeout...

Is there just that one entry or is there a second one starting with `/dev/cu.usbserial...`? It may behave differently.

**Comment by kzyapkov** [comment]
I tried 3 different USB-serial chips, all create a `/dev/tty.` and `/dev/cu.` device nodes, and both fail to accept the timeout-less break-setting `ioctl()`.

Using `send_break()` instead is a workaround. Not sure where to report the driver bug, but it probably affects all such devices.

**Comment by hoihu** [comment]
I can verify this (using a CP2104 USB <-> UART bridge chip). I'm also on OSX 10.11.4.

**Comment by SBeaver** [comment]
I have this issue but on linux (Arch x64). break_condition doesnt work, and send_break works differently than on windows.
For example, I use send_break(0.5) to wake up a device that is sleeping. On windows, this call takes 0.5 seconds and the device wakes up. On linux, the call takes no time (0.02 seconds roughly) and does not wake up the device. I use the workaround of sending send_break(500) on linux, it seems to work for my specific problem. In any case there has to be a bug there because it clearly states in the documentation the function should wait for the given duration before returning, but it doesn't.

**Comment by yoshpe** [comment]
The problem is because the TIOCSBRK and TIOCCBRK are not defined correctly by pyserial (termios doesn't have these attributes, thus it sets the default values 0x5427 and 0x5428)
Patch the file under serial/serialposix.py with the patched below:

```
--- serialposix.py
+++ serialposix.patched.py
@@ -240,8 +240,8 @@
 TIOCM_RTS_str = struct.pack('I', TIOCM_RTS)
 TIOCM_DTR_str = struct.pack('I', TIOCM_DTR)
 
-TIOCSBRK = getattr(termios, 'TIOCSBRK', 0x5427)
-TIOCCBRK = getattr(termios, 'TIOCCBRK', 0x5428)
+TIOCSBRK = getattr(termios, 'TIOCSBRK', 0x2000747b)
+TIOCCBRK = getattr(termios, 'TIOCCBRK', 0x2000747a)
 
 
 class Serial(SerialBase, PlatformSpecific):
```

**Comment by BobSki778** [comment]
> The problem is because the TIOCSBRK and TIOCCBRK are not defined correctly by pyserial (termios doesn't have these attributes, thus it sets the default values 0x5427 and 0x5428)
> Patch the file under serial/serialposix.py with the patched below:

This worked for me on MacOS 10.14.4.  How can we go about getting this rolled into the official pyserial?

**Comment by diamondman** [comment]
@BobSki778 Check out #431

**Comment by kurtmckee** [comment]
@zsquareplusc @andrewleech Please close this issue. It is 9 years old.

**Comment by dpgeorge** [comment]
It looks like this issue was fixed by 98c6a83f15ed79400a715086db115a81600c1b55 and fca918defddae5ecd1dc48dba0894717e33f8903, and those commits are part of release 3.5.

**Comment by kurtmckee** [comment]
@dpgeorge If that's the case, do you have rights to close this issue?
