### ISSUE TITLE
Import Failed under WinXP and Python 3.4

### ISSUE THREAD

**Issue by lijg** [pyserial/pyserial#132]
Hi, I've tried to use pyserial under WinXP with Python 3.4, but I cannot even import serial.

I installed pyserial-3.1.1 using `pip install pyserial`

here is the result
```
C:\Documents and Settings\Administrator>python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\serial\__init__.py", line 27, in <module>
    from serial.serialwin32 import Serial
  File "C:\Python34\lib\site-packages\serial\serialwin32.py", line 15, in <modul
e>
    from serial import win32
  File "C:\Python34\lib\site-packages\serial\win32.py", line 182, in <module>
    CancelIoEx = _stdcall_libraries['kernel32'].CancelIoEx
  File "C:\Python34\lib\ctypes\__init__.py", line 364, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python34\lib\ctypes\__init__.py", line 369, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'CancelIoEx' not found
```

**Comment by zsquareplusc** [comment]
I will not implement anything to make the latest version work under Windows XP, which is no longer supported by the vendor. Please use an old version of pySerial, e.g. https://pypi.python.org/pypi/pyserial/2.7

(`pip install pyserial==2.7`)

**Comment by mengyyy** [comment]
xp should use version below 3.1 （<=3.0.1）
python 3.4.4  2.7.12
