### ISSUE TITLE
_update_dtr_state throws Inappropriate ioctl for virtual serial port created by socat on OS X

### ISSUE THREAD

**Issue by MAKOMO** [pyserial/pyserial#133]
pyserial v3 fails to open a virtual serial port created by socat on OS X 

```
# brew install socat
# sudo socat -d -d -d -d -lf /tmp/socat pty,link=/dev/master,raw,echo=0,user=marko,group=staff pty,link=/dev/slave,raw,echo=0,user=marko,group=staff
# python
Python 2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
>>> serial.Serial(port="/dev/slave",baudrate=9600)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/serial/serialutil.py", line 182, in __init__
    self.open()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/serial/serialposix.py", line 265, in open
    self._update_dtr_state()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/serial/serialposix.py", line 595, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
IOError: [Errno 25] Inappropriate ioctl for device
```

Opening that serial port using
`serial.Serial(port="/dev/slave",baudrate=9600,dsrdtr=True,rtscts=True)`
works. Under pyserial v2.7 opening the port with either command works.

**Comment by zsquareplusc** [comment]
Hve you tested >= V3.1? because that version should ignore this error.

**Comment by MAKOMO** [comment]
Just checked again. I installed pyserial via pip and got v3.1.1. See below:

```
[Max:/Users/luther] python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 12:54:16) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
>>> serial.Serial(port="/dev/slave",baudrate=9600)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/serial/serialutil.py", line 182, in __init__
    self.open()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/serial/serialposix.py", line 265, in open
    self._update_dtr_state()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/serial/serialposix.py", line 595, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
IOError: [Errno 25] Inappropriate ioctl for device
>>> serial.VERSION
'3.1.1'
```

**Comment by zsquareplusc** [comment]
I see, it was a different ERRNO..

**Comment by MAKOMO** [comment]
Thanks for fixing this!

**Comment by ereOn** [comment]
@zsquareplusc I can also confirm that this solves the problem.

I've seen this was fixed on the 13 of June but the last release is from the 12. Would you have an ETA for the next release ?

Thanks for the good work !
