### ISSUE TITLE
#26 Fix: NameError: global name 'base' is not defined

### ISSUE THREAD

**Issue by glynhudson** [pyserial/pyserial#135]
Running pyserial 3.1.1 on ubuntu 14.4 (running on chrombook using crouton). 

**Issue:**

`python -m serial.tools.list_ports`

results in following error when ttyUSB device is connected:

```
python -m serial.tools.list_ports
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/serial/tools/list_ports.py", line 99, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/serial/tools/list_ports.py", line 83, in main
    iterator = sorted(comports())
  File "/usr/lib/python2.7/dist-packages/serial/tools/list_ports_posix.py", line 122, in comports
    return [(d, describe(d), hwinfo(d)) for d in devices]
  File "/usr/lib/python2.7/dist-packages/serial/tools/list_ports_posix.py", line 93, in describe
    return usb_lsusb_string(sys_usb)
  File "/usr/lib/python2.7/dist-packages/serial/tools/list_ports_posix.py", line 80, in usb_lsusb_string
    return base
NameError: global name 'base' is not defined
```

Manually applying fix #26 (which apparently got merged in 2011 but was not present in 3.1.1 on my system) fixed the issue: https://sourceforge.net/p/pyserial/patches/26/

Diff:

```
Index: trunk/pyserial/serial/tools/list_ports_posix.py
===================================================================
--- trunk/pyserial/serial/tools/list_ports_posix.py (revision 439)
+++ trunk/pyserial/serial/tools/list_ports_posix.py (working copy)
@@ -64,7 +64,8 @@
                 )

     def usb_lsusb_string(sysfs_path):
-        bus, dev = os.path.basename(os.path.realpath(sysfs_path)).split('-')
+        base = os.path.basename(os.path.realpath(sysfs_path))
+        bus, dev = base.split('-')
         try:
             desc = popen(['lsusb', '-v', '-s', '%s:%s' % (bus, dev)])
             # descriptions from device
```

Discussion on platformIO forum: https://community.platformio.org/t/chromebook-python-serial-error/385/3

Freeze output showing my manual change:

```
pip freeze
adium-theme-ubuntu==0.3.4
apt-xapian-index==0.45
backports-abc==0.4
backports.ssl-match-hostname==3.5.0.1
bottle==0.12.9
certifi==2016.2.28
cffi==1.6.0
chardet==2.0.1
click==5.1
colorama==0.3.7
command-not-found==0.3
cryptography==1.4
debtagshw==0.1
defer==1.0.6
derpconf==0.7.3
dirspec==13.10
enum34==1.1.6
esptool==0.1.0
futures==3.0.5
gyp==0.1
html5lib==0.999
httplib2==0.8
idna==2.1
ipaddress==1.0.16
libthumbor==1.3.1
lockfile==0.12.2
lxml==3.3.3
Nautilus-scripts-manager==1.7
ndg-httpsclient==0.4.1
  GNU nano 2.2.6                     File: /usr/lib/python2.7/dist-packages/serial/tools/list_ports_posix.py                                                 
oauthlib==0.6.1
oneconf==0.3.7.14.4.1
openshot==1.4.3
PAM==0.4.2
pexif==0.15
pexpect==3.1
Pillow==2.3.0
piston-mini-client==0.7.5
platformio==2.10.1
Pmw==1.3.2
pyasn1==0.1.9
pycparser==2.14
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pygobject==3.12.0
pyOpenSSL==16.0.0
pyserial==3.1.1
pysmbc==1.0.14.1
python-apt===0.9.3.5ubuntu2
python-debian===0.1.21-nmu2ubuntu2
python-magic==0.4.11
pytz==2016.4
pyxdg==0.25
reportlab==3.0
requests==2.10.0
sessioninstaller==0.0.0
singledispatch==3.4.0.3
six==1.10.0
software-center-aptd-plugins==0.0.0
statsd==3.2.1
system-service==0.1.6
tornado==4.3
Twisted-Core==13.2.0
Twisted-Web==13.2.0
unity-lens-photos==1.0
uptime==3.0.1
urllib3==1.7.1
wxPython==3.0.1.1
wxPython-common==3.0.1.1
xdiagnose===3.6.3build2
xmltodict==0.10.1
zope.interface==4.0.5
```

**Comment by zsquareplusc** [comment]
My guess is, that something got messed up here on your machine. Maybe an old er pyserial (python-serial) package is present on the system and gets used somehow. The line numbers do not match with the function names in the traceback above. And the current list port implementation does not have a `usb_lsusb_string` function anymore.

**Comment by glynhudson** [comment]
Ok, thanks. How can I fix this? Remove

python-serial?

- sent from my mobile device

**Comment by zsquareplusc** [comment]
I'd recommend that a Python application has only one version of each library on in its search path. Eiher installing one system wide is an option, or you could also use virtualenv/venv to create separate runtime environment for different projects.

**Comment by kurtmckee** [comment]
@zsquareplusc @projectgus Please close this issue. The project no longer has any of the referenced code in `list_ports_posix.py`.
