### ISSUE TITLE
Exception while cancel (python3)

### ISSUE THREAD

**Issue by devkral** [pyserial/pyserial#137]
I hit this exception while terminating pyserial (fix is at the end):
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/serial/tools/miniterm.py", line 463, in reader
    self.console.cancel()
  File "/usr/lib/python3.5/site-packages/serial/tools/miniterm.py", line 172, in cancel
    os.write(self.pipe_w, "x")
TypeError: a bytes-like object is required, not 'str'

The fix is:
    def cancel(self):
       os.write(self.pipe_w, "x")
should be:
    def cancel(self):
       os.write(self.pipe_w, b"x")

**Comment by devkral** [comment]
sry for the bad formatting. It is late.
pyserial version is:
3.1.1-1

**Comment by zsquareplusc** [comment]
Thank you
