### ISSUE TITLE
Unable to open /dev/ttyUSB1: IOError Broken Pipe

### ISSUE THREAD

**Issue by davidjb** [pyserial/pyserial#139]
I'm experiencing a reoccurrence of #67 -- oddly, it was fine for several months with pyserial 3.1 and Python 2.7.9 on my Raspberry Pi 2 running Debian Jessie.  However, the `IOError: [Errno 32] Broken pipe` error is reoccurring which is odd because the Pi has been untouched since applying pyserial 3.1 in March.

I tried upgrading to pyserial 3.1.1 but the following traceback still occurs:

```
python -m serial.tools.miniterm /dev/ttyUSB1
Traceback (most recent call last):
  File "./bin/py", line 41, in <module>
    _val, {}, "__main__", alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/telstra.mobile/eggs/pyserial-3.1.1-py2.7.egg/serial/tools/miniterm.py", line 930, in <module>
    main()
  File "/home/pi/telstra.mobile/eggs/pyserial-3.1.1-py2.7.egg/serial/tools/miniterm.py", line 886, in main
    serial_instance.open()
  File "/home/pi/telstra.mobile/eggs/pyserial-3.1.1-py2.7.egg/serial/serialposix.py", line 265, in open
    self._update_dtr_state()
  File "/home/pi/telstra.mobile/eggs/pyserial-3.1.1-py2.7.egg/serial/serialposix.py", line 595, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
IOError: [Errno 32] Broken pipe
```

Downgrading to pyserial 2.7 resolves the issue:

```
python -m serial.tools.miniterm /dev/ttyUSB1
--- Miniterm on /dev/ttyUSB1: 9600,8,N,1 ---
--- Quit: Ctrl+]  |  Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
```

The device is a USB 3G modem, a ZTE K3571.  Anything else in particular I should try for debugging?

**Comment by zsquareplusc** [comment]
"broken pipe" is not one of the errors that is "allowed" in the `open` function. Its usually seen when the connection to a device is interrupted (unplugged, intermittent contact)

You say that this is a modem, so it should support the control lines, it may even be better to open the serial port with hardware flow control enabled.

**Comment by wajdan846** [comment]
Im having the same problem while interfacing openbci with my ubuntu, 

I hope my dongle is fine

**Comment by jwilk** [comment]
Setting both `rtscts=True` and `dsrdtr=True` fixed it for me.
But AFAICS miniterm has only UI to set the former, not the latter.

**Comment by aifei7320** [comment]
jwilk was right, I having the same problem and follow jwilk's operation it works

**Comment by dima72** [comment]
to reinstall pyserial2.7 worked for me to sole **'Broken Pipe'** problem

`sudo pip install --force-reinstall pyserial==2.7`

**Comment by alexanderschulze** [comment]
Yes, same for me. It is working for v2.7, but not in the latest one (v3.4). Thanks @dima72

**Comment by Cabdulahi** [comment]
iam also facing this issues on ubuntu 18.4 
you dont need to look the pyserial ,it was your os issuess

**Comment by Cabdulahi** [comment]
iam also facing this issues on ubuntu 18.4 
you dont need to look the pyserial ,it was your os issuess

**Comment by Cabdulahi** [comment]
iam also facing this issues on ubuntu 18.4 
you dont need to look the pyserial ,it was your os issuess
