### ISSUE TITLE
 On Windws XP not support CancelIO

### ISSUE THREAD

**Issue by mengyyy** [pyserial/pyserial#148]
I just want to know which version  i can use in Windows xp (SP2).
Thanks a lot

**Comment by mengyyy** [comment]
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\serial\__init__.py", line 27, in <module>
    from serial.serialwin32 import Serial
  File "C:\Python27\lib\site-packages\serial\serialwin32.py", line 15, in <module>
    from serial import win32
  File "C:\Python27\lib\site-packages\serial\win32.py", line 182, in <module>
    CancelIoEx = _stdcall_libraries['kernel32'].CancelIoEx
  File "C:\Python27\lib\ctypes\__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'CancelIoEx' not found

**Comment by zsquareplusc** [comment]
Windows XP is not supported by pySerial 3.x, you could however [use an older version](http://pyserial.readthedocs.io/en/latest/pyserial.html#older-versions). I have added links to older versions on that page. e.g. 2.7 should work.

**Comment by WorldException** [comment]
https://github.com/WorldException/pyserial/commit/c4dd5a2790ac8482ca5bd8bf7547e96a2259186d

**Comment by ogurets** [comment]
I've had version 3.1.1 working fine on XP, you could try starting from this one.
