### ISSUE TITLE
get error on setRTS() after enabling hardwareflowcontrol

### ISSUE THREAD

**Issue by harryberlin** [pyserial/pyserial#152]
my system is a rasp 2 with osmc (debian and python 2.7)

on init i enable hardwareflowcontrol.
but by setRTS i get an error
`EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.IOError'>
Error Contents: (32, 'Broken pipe')
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/plugin.script.ibuscommunicator/service.py", line 4593, in <module>
main()
File "/home/osmc/.kodi/addons/plugin.script.ibuscommunicator/service.py", line 4490, in main
if not IBUS.connect():
File "/home/osmc/.kodi/addons/plugin.script.ibuscommunicator/service.py", line 674, in connect
self.serial_port.setRTS(0)
File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 527, in setRTS
fcntl.ioctl(self.fd, TIOCMBIC, TIOCM_RTS_str)
IOError: (32, 'Broken pipe')
-->End of Python script error report<--`

is it a bug, or is it not possible to set rts manually with activated hardwareflowcontrol?

the confuse thing is, after restarting the script, i don't get this error and the program is running.
does it mean the hardwareflowcontrol is enabled, or just skipped?

**Comment by zsquareplusc** [comment]
AFAIK it is usually *not* supported to control the control lines when HW flow control is enabled. Different drivers may also report different errors (errno). Though 'Broken pipe' is often used when the connection is interrupted.

pySerial 2.7 did only write the settings when they have changed, some drivers did not update all settings when that happened after `open()`. You could change a setting or use a more recent version of pySerial.

**Comment by harryberlin** [comment]
ok, thx for your answer. 
i'm using pySerial 3.1.1 already. 2.7 is the python version.
i tried the other hardwareflowcontrol dtsdsr and setDTR() undependently True without an error.

**Comment by diamondman** [comment]
@harryberlin Is this issue resolved? If so, mind closing it?

**Comment by harryberlin** [comment]
No, don't know how to solve.
