### ISSUE TITLE
rs485 not in pyserial

### ISSUE THREAD

**Issue by walchko** [pyserial/pyserial#159]
OS: macOS el capitan
Python: 2.7.12

I am trying to use rs485 using the example in the [docs](http://pyserial.readthedocs.io/en/latest/pyserial_api.html#rs485-support):

```python
import serial
ser = serial.Serial()
ser.rs485_mode = serial.rs485.RS485Settings()
ser.write(b'hello')
```

but I get:

```bash
Traceback (most recent call last):
  File "./ml-320.py", line 297, in <module>
    main()
  File "./ml-320.py", line 262, in main
    s.rs485_mode = serial.rs485.RS485Settings(
AttributeError: 'module' object has no attribute 'rs485'
```
when I run python I get:
```python
>>> import serial
>>> serial.__version__
'3.1.1'
>>> dir(serial)
['CR', 'EIGHTBITS', 'FIVEBITS', 'LF', 'PARITY_EVEN', 'PARITY_MARK', 'PARITY_NAMES', 
'PARITY_NONE', 'PARITY_ODD', 'PARITY_SPACE', 'PosixPollSerial', 'SEVENBITS', 'SIXBITS',
 'STOPBITS_ONE', 'STOPBITS_ONE_POINT_FIVE', 'STOPBITS_TWO', 'Serial', 'SerialBase',
 'SerialException', 'SerialTimeoutException', 'VERSION', 'VTIMESerial', 'XOFF', 'XON', '__builtins__',
 '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'importlib', 'io', 'iterbytes', 'os',
 'portNotOpenError', 'protocol_handler_packages', 'serial_for_url', 'serialposix', 'serialutil', 'sys',
 'time', 'to_bytes', 'writeTimeoutError']
```

where is the rs485 module???

This is the current version I installed using `pip`

**Comment by ldpgh** [comment]
For me it requires to add one more import statement in [test_rs485.py.txt](https://github.com/pyserial/pyserial/files/453898/test_rs485.py.txt) ...
```
import serial
from serial import rs485

ser=serial.Serial()
ser.rs485_mode=serial.rs485.RS485Settings()

print ser.rs485_mode
```
with the output
```
>>>python -i test_rs485.py
<serial.rs485.RS485Settings object at 0x023D1EB0>
```
My Python setup is ...
```
>>> import sys
>>> sys.version
'2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]'
```
with
```
>>> serial.__version__
'3.1.1'
```

**Comment by zsquareplusc** [comment]
I see, the import was missing, I've updated the documentation to mention that.
