### ISSUE TITLE
Missing semicolon in serialwin32.py

### ISSUE THREAD

**Issue by kbandla** [pyserial/pyserial#166]
Tested this on Windows 10, and Python 2.7
```
D:\>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import serial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python27\lib\site-packages\pyserial-3.1.1-py2.7.egg\serial\__init__.py", line 32, in <module>
    from serial.serialwin32 import Serial
  File "D:\Python27\lib\site-packages\pyserial-3.1.1-py2.7.egg\serial\serialwin32.py", line 330
    elif errorcode in (win32.ERROR_SUCCESS, win32.ERROR_IO_PENDING)
                                                                  ^
SyntaxError: invalid syntax
>>>
```

fixed in #164

**Comment by zsquareplusc** [comment]
Thank you
