### ISSUE TITLE
Serial port closed and can't open again！！！

### ISSUE THREAD

**Issue by wuyish** [pyserial/pyserial#171]
>>> import serial
>>> ser=serial.Serial("/dev/ttyUSB0",115200)
>>> ser.isOpen()
True
>>> ser.close()
>>> ser.isOpen()
False
>>> ser=serial.Serial("/dev/ttyUSB0",115200)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/serial/serialutil.py", line 236, in __init__
    self.open()
  File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 612, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
IOError: [Errno 5] Input/output error
>>> ser.isOpen()
False

**Comment by zsquareplusc** [comment]
can not reproduce this

Python 2.7.12, on Linux
```
>>> import serial
>>> serial.__version__
'3.2.1'
>>> s = serial.Serial('/dev/ttyUSB0')
>>> s
Serial<id=..., open=True>(...)
>>> s.close()
>>> s
Serial<id=..., open=False>(...)
>>> q = serial.Serial('/dev/ttyUSB0')
>>> q
Serial<id=..., open=True>(...)
>>> q.write("a")
1

```

**Comment by diamondman** [comment]
@wuyish Did you resolve your issue/did it become irrelevant? If either is the case, please close your issue. Otherwise, please post more information.

**Comment by thmna** [comment]
@wuyish Did you resolve your issue ? If you did, please share

**Comment by kurtmckee** [comment]
@zsquareplusc @projectgus Please close this issue. It is 9 years old and could not be reproduced.
