### ISSUE TITLE
termios.error: (22, 'Invalid argument') with PARITY_ODD/PARITY_EVEN

### ISSUE THREAD

**Issue by girst** [pyserial/pyserial#196]
Consider this example (sending AT command to UMTS modem):

```
import time
import serial

ser = serial.Serial(
    port='/dev/ttyUSB1',
    baudrate=9600,
    stopbits=serial.STOPBITS_TWO,
    bytesize=serial.EIGHTBITS,
    parity=serial.PARITY_ODD
)

ser.isOpen()

ser.write ("AT^SYSINFOEX\r".encode ())
time.sleep (.4)
print (ser.read (ser.inWaiting()))
ser.close ()
```

When `parity=serial.PARITY_ODD` is set, the program throws this exception:

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    parity=serial.PARITY_ODD
  File "/usr/lib/python3.5/site-packages/serial/serialutil.py", line 182, in __init__
    self.open()
  File "/usr/lib/python3.5/site-packages/serial/serialposix.py", line 251, in open
    self._reconfigure_port(force_update=True)
  File "/usr/lib/python3.5/site-packages/serial/serialposix.py", line 404, in _reconfigure_port
    [iflag, oflag, cflag, lflag, ispeed, ospeed, cc])
termios.error: (22, 'Invalid argument')
```

Setting `parity=` to `PARITY_NONE`, the exception doesn't throw. `PARITY_EVEN` also throws the exception. 

System: Fedora 25, tested both the repository version, as well as the pip version for python2 and python3. 

Any help is highly appreciated, thanks!

**Comment by tiwao** [comment]
Hello, 
I have same problem.
How did you solve this problem?
Could you tell me?

**Comment by ohhmy** [comment]
@tiwao I changed parity bit to NONE on the signal machine. and set  `parity=PARITY_NONE` on the serial.

**Comment by tiwao** [comment]
@ohhmy  
Thank you so much.
I See. you need not parity..
My target equipment requires even parity...
So, I need to set parity..

My hardware, which my program run on, has function of parity. 
pyserial does not support parity?
if so, do you know python serial library that supports parity function.

**Comment by tiwao** [comment]
@ohhmy 

Sorry..
it works..
my hardware configuration was wrong..
pyserial works well. ;-)

thank you very much.

**Comment by SillyFreak** [comment]
It seems I have a related problem. I'm running Raspbian on a Raspberry Pi 3 Model B v1.2 and Python 3.5.3; pyserial 3.4 is installed in a virtual environment the following is my test code (RX & TX are connected):

```
import serial

SERIAL_PARAMS = dict(
    baudrate=115200,
    bytesize=serial.EIGHTBITS,
    parity=serial.PARITY_EVEN,
    stopbits=serial.STOPBITS_ONE,
    timeout=1,
    xonxoff=False,
    rtscts=False,
    writeTimeout=None,
    dsrdtr=False,
    interCharTimeout=None,
)

s = serial.Serial('/dev/ttyS0', **SERIAL_PARAMS)
s.write(b'hello')
print(s.read(5))
s.close()
```

Using PARITY_NONE works consistently, but EVEN and ODD only work _once_, then OP's error occurs until I reboot.

I have tried picocom (`picocom -b 115200 -p ... /dev/ttyS0`) as well to check whether it's a pyserial problem, the behavior seems to be consistently this:

- using any parity in picocom works; I can quit and restart it, use different parities
- using pyserial without parity works
- after using pyserial at least once (regardless of parity), any further attempt to use parity causes an error
  - for pyserial, `termios.error: (22, 'Invalid argument')`
  - for picocom, `FATAL: failed to config device /dev/ttyS0: Cannot set the device attributes: Invalid argument`
- not using parity continues to work with both pyserial and picocom

**Comment by tiwao** [comment]
Hello,

I had same problem.

`/dev/ttyS0` of  Raspberry Pi 3 Model B does not support EVEN and ODD.
So, you need to use `/dev/ttyAMA0`.
However `/dev/ttyAMA0`  of  Raspberry Pi 3 Model B is bound to Bluetooth module.
In order to use `/dev/ttyAMA0`, you need to add the followings line into  `/boot/config.txt`.

```
dtoverlay=pi3-miniuart-bt
```

After reboot, you can use /dev/ttyAMA0 as physical serial port.

**Comment by tiwao** [comment]
sorry, I have no idea about it

**Comment by Batov** [comment]
Have same issue like @SillyFreak on 

- Linux raspberrypi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux
- Python 3.6.4
- pySerial 3.4

**Comment by FStefanni** [comment]
Still have the same issue: parity works only _once_ on Raspberry (I have a Pi3 model B with Python 3), then you have to "reset" somehow the serial (e.g. if I just run minicom to read the serial, and then return to python, it works).

Without parity, it always works.

**Comment by qoo00783** [comment]
I have same problem on pi4.
Like @tiwao said ttyS0 not support parity bit.
Following is my steps:
1. Upgrade system `sudo apt-get upgrade`
2. Edit `/boot/config.txt`
`enable_uart=1`
`core_freq=250`
`dtoverlay=miniuart-bt`
3. reboot

You can use ttyAMA0 now, and ttyS0 is bound to Bluetooth module.
References:
https://www.raspberrypi.org/documentation/configuration/uart.md

**Comment by maxelot** [comment]
I fixed the problem in a similar way as @qoo00783 for my Pi4.
I use PySerial for Modbus with `PARITY_ODD` or `PARITY_EVEN` for serial0 (ttyS0) over an RS485-hat
1. `sudo nano /boot/config.txt`
2. add `dtoverlay=disable-bt` to the bottom and save (this way the uart used for bluethooth is free and can be used for serial [at least that's my understanding])
3. `sudo reboot now`

Tested with Python3.7

**Comment by vu4rac0d3** [comment]
> I fixed the problem in a similar way as @qoo00783 for my Pi4.
> I use PySerial for Modbus with `PARITY_ODD` or `PARITY_EVEN` for serial0 (ttyS0) over an RS485-hat
> 
>     1. `sudo nano /boot/config.txt`
> 
>     2. add `dtoverlay=disable-bt` to the bottom and save (this way the uart used for bluethooth is free and can be used for serial [at least that's my understanding])
> 
>     3. `sudo reboot now`
> 
> 
> Tested with Python3.7

lol.. Just searched for that problem. The only diff is I use the Pi0, but everything else is exact the same.
lets try jour solution ;)

**Comment by zsquareplusc** [comment]
i've added a note about the raspi tho the FAQ.

the original question was not on a raspi though, but maybe that USB device did not support those parity settings.
can we close this?

**Comment by vadmium** [comment]
Here are my discoveries about how port settings like parity are set on Linux. In summary, if you change many port attributes at once with _tcsetattr_, the port may silently ignore some changes (like enabling parity with PARENB) that it doesn't like. But if the other port attributes have already been set and the only attributes you are changing are ones such as PARENB that it doesn't like, it may fail with EINVAL ("invalid argument"), depending on the C library and Linux distribution.

Python raises _termios.error_ if it sees this error (which isn't documented). But it does not check if all the attribute changes have stuck, so you won't see the exception if other port attributes (such as raw mode) haven't yet been set up.

In my case I was trying to substitute a pseudoterminal for a real UART-based port with PARITY_EVEN enabled. The solution was to omit the _parity_ parameter.

Posix <https://pubs.opengroup.org/onlinepubs/9699919799/functions/tcsetattr.html#tag_16_607_03> says

> The _tcsetattr_ function shall return successfully if it was able to perform any of the requested actions, even if some of the requested actions could not be performed. It shall set all the attributes that the implementation supports as requested and leave all the attributes not supported by the implementation unchanged. If no part of the request can be honored, it shall return -1 and set _errno_ to EINVAL.

The Linux man page <https://man7.org/linux/man-pages/man3/tcsetattr.3.html#RETURN_VALUE> says “_tcsetattr_ returns success if _any_ of the requested changes could be successfully carried out.”

Debian has patched _glibc_ so that _tcsetattr_ fails with EINVAL if changing an attribute such as PARENB does not stick, and no other attributes were changed <https://salsa.debian.org/glibc-team/glibc/-/blob/sid/debian/patches/any/local-tcsetaddr.diff>

Unpatched _glibc_ behaviour: <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=218131#30>

**Comment by philippoo66** [comment]
here is what I observerd:

I have a very simple py script:

```
import serial
import time

ser1 = serial.Serial('/dev/ttyS0',
        baudrate=4800,
        parity=serial.PARITY_EVEN,
        stopbits=serial.STOPBITS_TWO,
        bytesize=serial.EIGHTBITS,
        timeout=0)

print("opened.")
time.sleep(1)

ser1.close()
print("closed1:", ser1.closed)
time.sleep(1)
ser1.close()
print("closed2:", ser1.closed)
ser1=None
print("none")
```

when I run it for the first time I get this output:

```
opened.
closed1: False
closed2: False
none
```

The port works fine without problems even with PARITY_EVEN. But what is obvious is that the port does not close, no matter how hard you try. I tried arround for hours with different settings and calls but always the same - it stays open.

When I run the script again I get
```
Traceback (most recent call last):
  File "/home/phil/Downloads/ptest.py", line 4, in <module>
    ser1 = serial.Serial('/dev/ttyS0',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 332, in open
    self._reconfigure_port(force_update=True)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 517, in _reconfigure_port
    termios.tcsetattr(
termios.error: (22, 'Invalid argument')
```

after a reboot the same game: first time the port works great, does not close when it should and on the second try I get the error.

on a Pi2 I can repeat the script hundreds of times without any problem.

greetings!
Phil

**Comment by philippoo66** [comment]
> `/dev/ttyS0` of Raspberry Pi 3 Model B does not support EVEN and ODD.

that's not completely true. It works perfectly once a runtime. if you close the port you need to reboot befor opening it again.

**Comment by kurtmckee** [comment]
@zsquareplusc @dpgeorge Please close this issue. It is ~9 years old and cannot be diagnosed.

**Comment by dpgeorge** [comment]
It looks like certain serial devices don't support setting the parity.  That's not really a pyserial issue.
