### ISSUE TITLE
open/read/close quickly causes program crash

### ISSUE THREAD

**Issue by jerrys208** [pyserial/pyserial#219]
* running environment: Windows-7 / Python 3.5.2 (64) / PySerial 3.3
* reproduce script (not real program) -> not always happen:

``` python
import time
from serial import Serial

def read_next_frame(serial):
    try:
        frame_type = None
        while not frame_type:    # check serial.is_open here still hits the problem
            frame_type = serial.read(1)
    except:
        print('read end')

def test_open_read():
    serial = Serial(port='COM18', baudrate=115200)
    read_thread = threading.Thread(target=read_next_frame, args=(serial,))
    read_thread.start()
    time.sleep(0.1)    # let read thread do something wrong
    serial.close()
    read_thread.join()
    # if not delay here, next round test will be very likely to get PermissionError while opening serial port
    time.sleep(0.1)    

if __name__ == '__main__':
    print('test_open_read_crash')
    for i in range(300):    # not always happens 
        print('round: %s' % i)
        test_open_read()
```

* error 1 - APPCRASH:
```
Problem signature:
Problem Event Name: APPCRASH
Application Name:   python.exe
Application Version: 3.5.1150.1013
Application Timestamp:  576f0390
Fault Module Name:  ntdll.dll
Fault Module Version:   6.1.7601.18247
Fault Module Timestamp: 521eaf24
Exception Code: c0000005
Exception Offset:   0000000000053290
OS Version: 6.1.7601.2.1.0.256.4
Locale ID:  1028
```
* error 2 - PermissionError
```
Traceback (most recent call last):
  File "...tests/func/test_core_dev.py", line 77, in <module>
    test_open_read()
  File "...tests/func/test_core_dev.py", line 64, in test_open_read
    serial = Serial(port='COM18', baudrate=115200)
  File "...\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "...\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "...\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM18': PermissionError(13, '存取被拒。', None, 5)
```

thanks for your help :)

**Comment by twatteyne** [comment]
looks like I have the same issue, using:
- Windows-7-6.1.7601-SP1, AMD64
- Python 2.7.14
- PySerial 3.4

@jerrys208, any development on your side?
