### ISSUE TITLE
Problem with bluetooth serial communication

### ISSUE THREAD

**Issue by leomikezee** [pyserial/pyserial#221]
I connect my RPi to my PC by bluetooth and use `sudo rfcomm bind rfcomm0 AA:BB:CC:DD:EE` to setup a serial connection.

However, when I try to open miniterm with this port by `python3 -m serial.tools.miniterm /dev/rfcomm0 115200`, I got serial.serialutil.SerialException. If I open the port in my PC by putty or other serial communication software first, and then open miniterm on RPi, pyserial will not raise the SerialException.

I have also tried use minicom and it works fine whether I connect to the port from my PC first or not. `minicom -D /dev/rfcomm0 115200`.

**Comment by leomikezee** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/Mespere/MesperePi/lib/python3.4/site-packages/serial/tools/miniterm.py", line 445, in reader
    data = self.serial.read(self.serial.in_waiting or 1)
  File "/home/pi/Mespere/MesperePi/lib/python3.4/site-packages/serial/serialposix.py", line 508, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```
