### ISSUE TITLE
Running 'python setup.py install' (pyserial)aborts with Exception: (TypeError: __init__() takes exactly 2 arguments (4 given))

### ISSUE THREAD

**Issue by Tirumala7** [pyserial/pyserial#233]
I am Installing pyserial-3.3. Installed using the command pip install pyserial. After that I Run the command python setup.py install . I Have also tried to install pyserial 3.2.1 , then also it gave the same error. It aborts with exception Error:
```
Installed /usr/lib/python2.7/site-packages/pyserial-3.3-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 98, in <module>
    scripts=['serial/tools/miniterm.py'],
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73                                                                                        , in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 10                                                                                        1, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", li                                                                                        ne 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", li                                                                                        ne 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", li                                                                                        ne 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", li                                                                                        ne 701, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)
```
Please Help!

**Comment by geeklady2** [comment]
Any solution to this.   I'm having the same issue after running yum update on my centos 7.4 machine.

**Comment by zsquareplusc** [comment]
My guess would be that there is an old `setuptools` package. Was that also installed via `pip`? is it up-to-date?

the OP mentions use of "setup.py install" after already running "pip install pyserial". The later is enough when installing, no need to run setup.py manually again.

**Comment by geeklady2** [comment]
In my hunting I came across someone with the same issue. They suggested it was a gcc issue.   Anyway my fix was to manually install python27 manually and then everything else.

I had done a yum update and things didn't work after that so all was very up to date. It's working now which is all that matters. Thanks for your suggestion though.

**Comment by jazzl0ver** [comment]
```
yum remove python-setuptools.noarch
pip uninstall setuptools
pip install setuptools
```
did the trick for me
