### ISSUE TITLE
_reconfigure_port is not implemented in Jython backend Serial class 

### ISSUE THREAD

**Issue by jdstroy** [pyserial/pyserial#275]
The `Serial` class in `serialjava.py` does not implement _reconfigure_port, similar to issue #127 .  Just as with issue #127, this causes `serialutil.py` to raise an `AttributeError` when setting the baudrate:

```
Traceback (most recent call last):
  File "esptool.py", line 2524, in <module>
    _main()
  File "esptool.py", line 2517, in _main
    main()
  File "esptool.py", line 2517, in _main
    main()
  File "esptool.py", line 2246, in main
    esp = chip_class(args.port, initial_baud)
  File "esptool.py", line 183, in __init__
    self._set_port_baudrate(baud)
  File "esptool.py", line 187, in _set_port_baudrate
    self._port.baudrate = baud
  File "esptool.py", line 187, in _set_port_baudrate
    self._port.baudrate = baud
  File "C:\Win32\Python\jython2.7.0\Lib\site-packages\serial\serialutil.py", line 295, in baudrate
    self._reconfigure_port()
AttributeError: 'Serial' object has no attribute '_reconfigure_port'
```

It appears that `Serial._reconfigurePort` exists in `serialjava.py` and serves the same purpose as `_reconfigure_port`.

**Comment by dpgeorge** [comment]
Fixed by 8ec5f07e01892fbbfd248b1914a8cb637d3976af
