### ISSUE TITLE
Baudrate 2048000 doesn't work under linux 

### ISSUE THREAD

**Issue by PaulPL2017** [pyserial/pyserial#284]
Hi, I've tried to use Baudrate 2048000 under Linux (Linux raspberrypi 4.9.35-v7+) with an ST Microcontroler (SPC5) and it doesn't connect.

_### Traceback (most recent call last):
  File "Pre_ABC.py", line 40, in <module>
    ser.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 285, in open
    self._reconfigurePort()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 420, in _reconfigurePort
    set_special_baudrate(self, custom_baud)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 52, in set_special_baudrate
    buf[6] = buf[7] / baudrate
TypeError: integer argument expected, got float__

**Comment by zsquareplusc** [comment]
Guessing this is an older version of pySerial?! You could uninstall the one from the package manager and use `pip install pyserial` to get the latest from pypi.

Also that baud rate is quite high, you may run into problems with that (electrical and/or performance).

**Comment by DavidLutton** [comment]
Could the specifications (of your hardware) intend for a multiplier of 1000000 instead of 1024000 to be used for the baud rate
[serialposix.py](https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py#L109-L109) has a constant for **2000000** but not 2048000

**Comment by PaulPL2017** [comment]
Specification to device define baud rate 2048000. I tried baud rate 2000000. Transmision is correct.
Maybe change baud rate isn't critical error on transmision.
