### ISSUE TITLE
Calling serial.tools.list_ports.comports() blocks port opening (windows, only concerned when threading used)

### ISSUE THREAD

**Issue by alikin12** [pyserial/pyserial#309]
Only tested on windows:
The following example code leads to a PermissionError after some time when trying to open the port. This is caused by the comport() function in the second thread which seems to block the file handle at some point.

`import threading
import serial
import serial.tools.list_ports

def a():
	try:
		while(1):
			ser=serial.Serial("COM4")
			ser.close()
	except Exception as e:
		print(e)
def b():
	try:
		while(1):
			ports=serial.tools.list_ports.comports()
	except Exception as e:
		print(e)

t1 = threading.Thread(target=a)
t1.daemon = True
t2 = threading.Thread(target=b)
t2.daemon = True
t1.start()
t2.start()
while(1):
	pass`

**Comment by pranjaldronzer** [comment]
I have also seen this issue. I am getting PermissionError(13, 'Access is denied.', None, 5) issue. I triggered following code:
```py
while True:
     ports = list(serial.tools.list_ports.comports())
     for p in ports:
         if 'COM4' in p:
             ser=serial.Serial(port='COM4', baudrate=int(9600),timeout=5, write_timeout=5)
             break
```
This is mt traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "P:\Program Files (x86)\Python\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "P:\Program Files (x86)\Python\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "P:\Program Files (x86)\Python\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM4': PermissionError(13, 'Access is denied.', None, 5)
```

**Comment by marcardenas** [comment]
> I have also seen this issue. I am getting PermissionError(13, 'Access is denied.', None, 5) issue. I triggered following code:
> 
> ```python
> while True:
>      ports = list(serial.tools.list_ports.comports())
>      for p in ports:
>          if 'COM4' in p:
>              ser=serial.Serial(port='COM4', baudrate=int(9600),timeout=5, write_timeout=5)
>              break
> ```
> 
> This is my traceback:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 5, in <module>
>   File "P:\Program Files (x86)\Python\lib\site-packages\serial\serialwin32.py", line 31, in __init__
>     super(Serial, self).__init__(*args, **kwargs)
>   File "P:\Program Files (x86)\Python\lib\site-packages\serial\serialutil.py", line 240, in __init__
>     self.open()
>   File "P:\Program Files (x86)\Python\lib\site-packages\serial\serialwin32.py", line 62, in open
>     raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
> serial.serialutil.SerialException: could not open port 'COM4': PermissionError(13, 'Access is denied.', None, 5)
> ```

It seems that on the next iteration of your while loop it will try to open the same port again, which will throw the PermissionError
