### ISSUE TITLE
Baud rate of 4.000.000 not working on macOS High Sierra (10.13.1)

### ISSUE THREAD

**Issue by maziarz** [pyserial/pyserial#323]
I know this is a common issue on macOS, but i am wondering if there is a hack or workaround to increase the speed to 4.000.000 baud?

```
import serial
ser_port = '/dev/tty.usbserial-A106OQ06'
ser = serial.Serial(ser_port, 4000000)
```

```
Traceback (most recent call last):
  File "rs232_test.py", line 12, in <module>
    ser = serial.Serial(ser_port, 4000000)
  File "/Users/testUser/.pyenv/versions/3.6.0/lib/python3.6/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/Users/testUser/.pyenv/versions/3.6.0/lib/python3.6/site-packages/serial/serialposix.py", line 272, in open
    self._reconfigure_port(force_update=True)
  File "/Users/testUser/.pyenv/versions/3.6.0/lib/python3.6/site-packages/serial/serialposix.py", line 442, in _reconfigure_port
    self._set_special_baudrate(custom_baud)
  File "/Users/testUser/.pyenv/versions/3.6.0/lib/python3.6/site-packages/serial/serialposix.py", line 190, in _set_special_baudrate
    fcntl.ioctl(self.fd, IOSSIOSPEED, buf, 1)
OSError: [Errno 22] Invalid argument
```

**Comment by guerriky** [comment]
Hello,

As you can see in the file referenced in the exception:

```
elif plat[:6] == 'darwin':   # OS X
    import array
    IOSSIOSPEED = 0x80045402  # _IOW('T', 2, speed_t)

    class PlatformSpecific(PlatformSpecificBase):
        osx_version = os.uname()[2].split('.')
        # Tiger or above can support arbitrary serial speeds
        if int(osx_version[0]) >= 8:
            def _set_special_baudrate(self, baudrate):
                # use IOKit-specific call to set up high speeds
                buf = array.array('i', [baudrate])
fcntl.ioctl(self.fd, IOSSIOSPEED, buf, 1)
```

The supported baudrate values for OS X come directly from the _kernel driver_ itself.

At least, that's what I seem to keep finding everywhere, see:

https://discussions.apple.com/thread/1587991?start=0&tstart=0

By the looks of it, there is no easy workaround, certainly not one that can be implemented within python itself.

Maybe you can try finding alternative drivers? I'm no mac expert, but this article might give you a few pointers:

https://spin.atomicobject.com/2013/06/23/baud-rates-ftdi-driver-mac/

Hope this helped.

**Comment by UmbraTek** [comment]
I also have this problem。
I use the pyserial in win10 with 5000000 baud rate , it is ok，but it is not work in macos.
Is this problem solved now

**Comment by melonmouse** [comment]
On macOS ventura, I could construct and read out a `Serial` object with `baudrate=460800`. But the data was garbage (which wasn't the case on older versions of macOS), and upon closer inspection, I discovered the baudrate was silently being changed to a lower (incorrect) value. It would be nice if pySerial would throw an error - the current behavior seems to be a bug.

Opening a connection with `cu` did throw an error mentioning that the baudrate was not available.
`sudo cu -s 460800 -l /dev/tty[...]`.

As a workaround, I was able to open a connection and change the baudrate while it was already open.
`cat /dev/cu.usbserial`, then update the baud rate in another terminal `stty -f /dev/cu.usbserial 460800`. [Relevant thread](https://stackoverflow.com/questions/5539192/how-to-set-the-baud-rate-for-macs-in-a-terminal) on stackoverflow.

P.S. pyserial is awesome!
