### ISSUE TITLE
TypeError: an integer is required during read operation

### ISSUE THREAD

**Issue by guerriky** [pyserial/pyserial#328]
Hello,

I am writing a python driver for a USB serial device.

I'm using pyserial latest version on python 2.7.

I open the port like this:

```
self.serport = serial.Serial()
self.serport.port = self.port
self.serport.baudrate = self.baudrate
self.serport.timeout = self.timeout
self.serport.open()
```

And perform a series of read operations like this:

`data = self.serport.read(int(1)).decode()`

Some times, during normal operation, I get the following exception

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/ssd/buildroot/build_clb0005_po_nobk/target/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/ssd/buildroot/build_clb0005_po_nobk/target/usr/lib/python2.7/threading.py", line 754, in run
  File "/root/python/app/my_driver.py", line 101, in _read
    data = self.serport.read(int(1)).decode()
  File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 457, in read
    buf = os.read(self.fd, size - len(read))
TypeError: an integer is required
```

Further investigation reveals the culprit to be the `self.fd` value being None, as evidenced by the following print statement:

```
type fd: <type 'NoneType'>
type size: <type 'int'>
type len read: <type 'int'>
```

Adding an exception handler with retry is apparently enough to fix this issue.

Any patch available for the serial library?

Thank you

**Comment by zsquareplusc** [comment]
Well `fd` should not be `None` unless the port is closed. Maybe it is closed by accident (other threads?)?
