### ISSUE TITLE
device reports readiness to read but returned no data (device disconnected or multiple access on port?

### ISSUE THREAD

**Issue by anilkunchalaece** [pyserial/pyserial#341]
I'm trying simple Arduino Python Communication.
Computer is not receiving any data via pySerial. If i Try with Arduino Serial Monitor or Putty Data is receiving.

Complete Error is 
```
  File "checkData.py", line 16, in <module>
    readFromPort(arduinoData)
  File "checkData.py", line 11, in readFromPort
    reading = ser.readline().decode()
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 475, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
```
Google search gives me [https://askubuntu.com/questions/680473/ubuntu-14-04-usb-serial-port-device-reports-readiness-to-read-but-returned-n?](this) link . I tried with 3 different kernels but no luck (iam unable to install kernel specified in the answer)

**Comment by CodyOnGitHub** [comment]
Did you find a solution?
I've got a very similar problem.
My python code is communicating with Arduino, too.
It works several times and then it casts the same Error you have.

here is the code line which is initializing the connection:  
```
arduino = serial.Serial('/dev/ttyUSB1', 9600, timeout=1)
```
And here is the main loop:

``` run = input("Press Enter to Start: ")
print("writing")
arduino.write(bytes(json.dumps(gw_data),  'utf-8'))
while True:
    # try:
    content=arduino.readline()
    if(len(content) !=0):
        print(getValuesFromJson("ip", content))
        if(getValuesFromJson("ip", content)!=currentIP):
            print("IP ist anders")
            currentIP=getValuesFromJson("ip", content)
            arduino.write(bytes(json.dumps(gw_data),  'utf-8'))
        else:
            print("IP ist gleich")
    # except:
        # print("error")```
        
this is the output:
```
Reading ip...
Press Enter to Start: 
writing
192.168.30.219
IP ist gleich
Traceback (most recent call last):
  File "/home/ssv/Documents/Praxisphase/projekt_2_wifi_app/gateway_config_on_device/gateway/send_ip_to_serial.py", line 53, in <module>
    content=arduino.readline()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)```
