### ISSUE TITLE
RFC 2217 not working with pyserial-asyncio

### ISSUE THREAD

**Issue by makuser** [pyserial/pyserial#395]
Unfortunately the RFC 2217 transport can not yet be used with pyserial-asyncio.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 212, in coro
    res = func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/serial_asyncio/__init__.py", line 410, in create_serial_connection
    ser = serial.serial_for_url(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/serial/__init__.py", line 88, in serial_for_url
    instance.open()
  File "/usr/local/lib/python3.6/site-packages/serial/rfc2217.py", line 484, in open
    self._reconfigure_port()
  File "/usr/local/lib/python3.6/site-packages/serial/rfc2217.py", line 505, in _reconfigure_port
    raise NotImplementedError('write_timeout is currently not supported')
NotImplementedError: write_timeout is currently not supported
```

**Comment by zsquareplusc** [comment]
mm. that probably requires an asyncio version of the `rfc2217` module... it probably fails with other urlhandler too as those usually do I/O and none of them uses asyncio... all the URL handlers probably need to be re-implemented in `pySerial-asyncio`...
