### ISSUE TITLE
OSError: [Errno 5] Input/output error (Arduino)

### ISSUE THREAD

**Issue by Dentrax** [pyserial/pyserial#401]
Thıs code works great when I connect the **Arduino** to serial port. But in the loop, if I disconnect the Arduino from the USB, It throw an error.

Is my `read_from_port` function correct? How to control most accurate and correct way when the _serialport_ has been disconnected from the _USB_? (I don't want to use the **try-catch** structure while controlling that)

```
def read_from_port(ser):
    while True:
        connected = ser.isOpen()
        if (connected):
            if (ser.readable() and ser.in_waiting > 0):
                incoming = ser.read(ser.in_waiting).decode('ascii')
                on_data_received(incoming)
        else:
            return

        time.sleep(0.1)
```

```
    thread = threading.Thread(target=read_from_port, args=(ser,))
    thread.start()
```

**Error**

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "serialport/serialport.py", line 74, in read_from_port
    if (ser.readable() and ser.in_waiting > 0):
  File "/home/dentrax/.local/lib/python3.7/site-packages/serial/serialposix.py", line 467, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
OSError: [Errno 5] Input/output error
```

**Comment by zsquareplusc** [comment]
I see no way around using `try-except` to catch the error..

note that `readable()` always returns `True`, threfore the example above will constantly call `in_waiting` and use CPU even if there is nothing to read. I usually use `read(1)` to make it blocking until something arrives.

[serial.threaded.ReaderThread](https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.threaded.ReaderThread) provides a reader thread with callbacks on disconnect and CPU friendly reading.

**Comment by nnnayeem** [comment]
@Dentrax did you find your solution?

**Comment by Dentrax** [comment]
@nnnayeem Actually, no. But `try-catch` approach is fixed my problem. Please see [here](https://github.com/Dentrax/MMM-ArduPort/blob/master/arduport/arduino.py#L78). I don't know how to fix it without a use `try-catch`.

**Comment by nnnayeem** [comment]
@Dentrax thanks a lot. That solved my issue.

**Comment by nnnayeem** [comment]
I have the exact same problem like you and it solved my problem. Why don't you want to use try-catch? The error is an exception created by disconnecting your arduino. If you want to catch the error you have to use try catch.

**Comment by Dentrax** [comment]
@nnnayeem I don't like the use of `try-catch` in general. Because we do not handle the errors that occur in the code if `try-catch` was used. My advice is to use it as a final solution if bug is unable to unresolvable.

**Comment by MuhammetOzturk** [comment]
try-except blogunda portu yeniden kapatip acarsan duzeliyor.
