### ISSUE TITLE
Incompatbility with MSYS2 based python install

### ISSUE THREAD

**Issue by amoose136** [pyserial/pyserial#407]
My build environment on windows is setup around MSYS2 but pyserial doesn't seem to work MSYS2.

```
~ ❯ python -c "from serial.tools import list_ports"
don't know how to enumerate ttys on this system.
! I you know how the serial ports are named send this information to
! the author of this module:

sys.platform = 'msys'
os.name = 'posix'
pySerial version = 3.4

also add the naming scheme of the serial ports and with a bit luck you can get
this module running...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/usr/lib/python3.7/site-packages/serial/tools/list_ports_posix.py", line 112, in <module>
    raise ImportError("Sorry: no implementation for your platform ('{}') available".format(os.name))
ImportError: Sorry: no implementation for your platform ('posix') available
~ ❯
```
Looking in site-packages/serial/tools/list_ports_posix.py I can see there is no handling for the case of sys.platform = 'msys'

Changing line 33 from `elif plat == 'cygwin':       # cygwin/win32` to `elif plat == 'cygwin' or plat == 'msys':       # cygwin/win32/msys2` seems to fix things but I'm no expert on how any of this works.

**Comment by monstaruos** [comment]
Hi @amoose136 
Appending `or plat == 'msys'` is working fine on my end.
Thank you.

**Comment by nhatkhai** [comment]
Would these patch help?
[cygwin.tar.gz](https://github.com/pyserial/pyserial/files/6380638/cygwin.tar.gz)
