### ISSUE TITLE
Pypy error with pyserial

### ISSUE THREAD

**Issue by joker25** [pyserial/pyserial#427]
Pyserial fails while connecting when using pypy 7.1.1

Unhandled exception during connect
Traceback (most recent call last):
  File "/opt/klipper/klippy/klippy.py", line 137, in _connect
    cb()
  File "/opt/klipper/klippy/mcu.py", line 611, in _connect
    self._serial.connect()
  File "/opt/klipper/klippy/serialhdl.py", line 61, in connect
    self.serialport, self.baud, timeout=0, exclusive=True)
  File "/opt/klipper/venv/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/opt/klipper/venv/site-packages/serial/serialposix.py", line 272, in open
    self._reconfigure_port(force_update=True)
  File "/opt/klipper/venv/site-packages/serial/serialposix.py", line 442, in _reconfigure_port
    self._set_special_baudrate(custom_baud)
  File "/opt/klipper/venv/site-packages/serial/serialposix.py", line 121, in _set_special_baudrate
    fcntl.ioctl(self.fd, TCGETS2, buf)
OverflowError: long int too large to convert to int

**Comment by ksunden** [comment]
What is the baud rate you are trying to set?

What platform are you on? (particularly interested in 32 vs 64 bit)

The error makes it sound like you are setting it to something  > `2**31` (2147483648), which would be rather large for almost any realistic communication protocol (half a nanosecond per bit), ~2 GHz.

Can be done, but rather fast, especially if traversing over a distance.

**Comment by ksunden** [comment]
Looking a little closer at the lines surrounding the last call in the stack, that line _shouldn't_ depend on the actual baud rate, I will also point to the comment:

https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py#L140-L141

Perhaps something in the Pypy implementation of `fcntl.ioctl` does not allow for over size buffer, where CPython is tolerant of it. 

At any rate, the whole function `_set_special_baudrate` can be avoided by using one of the standard baudrates:

```python
>>> serial.Serial.BAUDRATES
(50, 75, 110, 134, 150, 200, 300, 600, 1200, 1800, 2400, 4800, 9600, 19200, 38400, 57600, 115200, 230400, 460800, 500000, 576000, 921600, 1000000, 1152000, 1500000, 2000000, 2500000, 3000000, 3500000, 4000000)
```
If that can work for the application in mind. (It's a workaround, not a fix, but not sure the fix lies in PySerial from a first glance)

**Comment by DanielJoyce** [comment]
Well Joker posted this in https://github.com/KevinOConnor/klipper/issues/1602

> Solved, the problem is in PySerial.
> 
> site-packages/serial/serialposix.py
> TCGETS2 = 0x802C542A has to be changed to TCGETS2 = -2144578518
> 
> apparently, PyPy cant convert it to a 32-bit integer, because it doesnt know unsigned integers

**Comment by mmirate** [comment]
I think that this issue has been solved, the correct way, since PyPy v7.3.7 (released October 2021): https://foss.heptapod.net/pypy/pypy/-/issues/3568.

**Comment by kurtmckee** [comment]
@zsquareplusc @andrewleech Please close this issue. It was being caused by a `fcntl.ioctl` bug in a now-unsupported version of PyPy.
