### ISSUE TITLE
Reusing exception instances stacks their tracebacks

### ISSUE THREAD

**Issue by dequis** [pyserial/pyserial#437]
This was a fun one to debug, we have an exception handler that waits for a few seconds and calls the main function again (with exponential backoff and all the bells and whistles)

When it fails with exceptions from pyserial, the traceback starts getting longer every time it fails.

Here's some minimal reproduction steps:

```
$ python
Python 3.7.3 (default, Mar 26 2019, 21:43:19)
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from serial import Serial
>>> a = Serial()
>>> a.write('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dx/test/venv/lib/python3.7/site-packages/serial/serialposix.py", line 554, in write
    raise portNotOpenError
serial.serialutil.SerialException: Attempting to use a port that is not open
>>> a.write('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dx/test/venv/lib/python3.7/site-packages/serial/serialposix.py", line 554, in write
    raise portNotOpenError
  File "<stdin>", line 1, in <module>
  File "/home/dx/test/venv/lib/python3.7/site-packages/serial/serialposix.py", line 554, in write
    raise portNotOpenError
serial.serialutil.SerialException: Attempting to use a port that is not open
>>> a.write('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dx/test/venv/lib/python3.7/site-packages/serial/serialposix.py", line 554, in write
    raise portNotOpenError
  File "<stdin>", line 1, in <module>
  File "/home/dx/test/venv/lib/python3.7/site-packages/serial/serialposix.py", line 554, in write
    raise portNotOpenError
  File "<stdin>", line 1, in <module>
  File "/home/dx/test/venv/lib/python3.7/site-packages/serial/serialposix.py", line 554, in write
    raise portNotOpenError
serial.serialutil.SerialException: Attempting to use a port that is not open
```

With more complex call flows this looks even more confusing, with the traceback jumping from the exception point to outside the exception handler, with nothing connecting those pairs of frames.

I think this is due to the fact that portNotOpenError is an instance of an exception that exists at the module level, so reusing that instance will keep the traceback from the previous time it was used. It should probably be a class instead.

I can send a pull request with a fix for this later.

**Comment by zsquareplusc** [comment]
That is one of the left overs from the Python 1.5.2 times with string exceptions (it once was just a string) :-) A cleaned up version should raise a new exception in all the places where the object is now reused (I would not make a helper function).

... and hope that no one uses `serial.portNotOpenError` in user code... but it was never mentioned in the docs anyway, so removing it should be OK.

**Comment by j123b567** [comment]
To remove the memory leak, there is simple workaround. (replace serialposix with your platform)

```python
import serial

serial.serialposix.writeTimeoutError = serial.SerialTimeoutException
serial.serialposix.portNotOpenError = serial.SerialException
```
