### ISSUE TITLE
Raspberry pi 3 and waveshare HAT Broken Pipe Error

### ISSUE THREAD

**Issue by vanvince** [pyserial/pyserial#438]
Hello everyone, 

I am working on a new HAT, SIM7000E NB-IoT HAT, and I'm trynig to connect to it through pySerial 3.4. I already have experience with pySerial, I already used it with another waveshare hat onto the same raspberry PI3. So, I take the same code and try to communicate with it. At the very start the terminal show me out this error: 
Traceback (most recent call last):
  File "newModule.py", line 7, in <module>
    _serial.open()
  File "/home/pi/.local/lib/python3.5/site-packages/serial/serialposix.py", line 286, in open
    self._update_dtr_state()
  File "/home/pi/.local/lib/python3.5/site-packages/serial/serialposix.py", line 634, in _update_dtr_state
    fcntl.ioctl(self.fd, TIOCMBIS, TIOCM_DTR_str)
BrokenPipeError: [Errno 32] Broken pipe

Onestly I don't understand the error's meaning. Anyone can help me? Below there is  the setup code:
` import serial

_serial = serial.Serial()      

_serial.port = "/dev/ttyUSB2"
_serial.open()
_serial.flushInput()
_serial.flushOutput()

_serial.addr = None

_serial.baudrate = 115200
_serial.bytesize = serial.EIGHTBITS
_serial.parity = serial.PARITY_NONE

_serial.timeout = 0
_serial.xonxoff = False
_serial.rtscts = True
_serial.dsrdtr = True
_serial.writeTimeout = 2 `

P.S. surfing internet I've already found a different solution with 
`_serial.rtscts = True
_serial.dsrdtr = True`
but this doesn't work for me. 

thanks in advance,
Vincenzo

**Comment by Tbo-Gee** [comment]
Hi, did you figure it out eventually. I have the same issue.

**Comment by kurtmckee** [comment]
As far as I can see from searching the internet, `BrokenPipeError` occurs when Python is attempting to write something but the receiving end has closed the connection.

@zsquareplusc @projectgus I recommend closing this issue. It is 6 years and cannot be diagnosed further.
