### ISSUE TITLE
When write value and get value for some time, throw ClearCommError failed (PermissionError(13, 'Access denied', None, 5)

### ISSUE THREAD

**Issue by peterhsu2018** [pyserial/pyserial#446]
I've created a desktop UI by PySide2, then communicate to USB device by pyserial, but read/write data for some time, i got the error as:

    Traceback (most recent call last):
        File "C:\Users\t\Desktop\test\tabWidget.py", line 160, in timeTick
            bTemp.append(float(setCommand(self.mainwindow.ser, 'drum_temp')))
        File "C:\Users\t\Desktop\test\utils.py", line 88, in setCommand
            while serialObj.inWaiting() > 0:
        File "C:\Users\t\Anaconda3\lib\site-packages\serial\serialutil.py", line 590, in inWaiting
            return self.in_waiting
        File "C:\Users\t\Anaconda3\lib\site-packages\serial\serialwin32.py", line 257, in in_waiting
            raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
        serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'Access denied', None, 5)

First of all, i open the serial port when click the 'connect' button, then read/write data to device by one function. Sometimes throws the error when initialize some commands to device, or write command to read data from device.

Something weird is my laptop run the code is fine, but another laptop from my colleague always throws this error. And use the administrator to run code on command line, same result.

This is the environment:

- Windows 10 64-bit
- python 3.6.8 -> conda create -n py36 python=3.6
- PySide2 5.13.0
- pyserial 3.4
- pip 19.1.1

And the read/write function as follow:

    def setCommand(serialObj, command):
        try:
            if serialObj is not None and serialObj.isOpen():
                serialObj.flushInput()
                byteData = bytes()
                if len(command) > 0:
                    serialObj.write(command.encode() + '\r'.encode())
                    time.sleep(0.1)
                    while serialObj.inWaiting() > 0:
                        byteData += serialObj.read(serialObj.inWaiting()) 
            return byteData.decode('ascii').rstrip('\r\n')
        except Exception:
            traceback.print_exc()
            pass
        return None

This is serial setting

    serialObj = serial.Serial(
        port='COM3',
        baudrate=57600,
        parity=serial.PARITY_NONE,
        stopbits=serial.STOPBITS_ONE,
        bytesize=serial.EIGHTBITS,
        timeout=0.5,
        writeTimeout=0)

I expect the code will run on any laptop, anyone can help me?

**Comment by bytesfold** [comment]
I am got same promble，i see my colleague Serial Port driver version is 
![image](https://user-images.githubusercontent.com/65302069/83939062-607b7900-a80c-11ea-837f-b8db864efaf9.png)
but me 
![image](https://user-images.githubusercontent.com/65302069/83939068-6b360e00-a80c-11ea-83a4-ea5bf5e1e88f.png)
maybe update driver can solve your problem
