### ISSUE TITLE
[Errno 5] Input/output error USB0 Raspberry pi 4

### ISSUE THREAD

**Issue by pawelpetruch** [pyserial/pyserial#471]
Hi,

When running the following code on RPi 4:

```
#!/usr/bin/env python
import time
import serial

ser = serial.Serial(port='/dev/ttyUSB0', baudrate=128000)

time.sleep(1)
ser.write(5)
```

I get:

`
 Traceback (most recent call last):
  File "write_serial.py", line 8, in <module>
    ser.write(5)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 571, in write
    raise SerialException('write failed: {}'.format(e))
serial.serialutil.SerialException: write failed: [Errno 5] Input/output error
`

When tested on a RPi 2 with the same device being hooked up it didn't throw any exceptions. 

When I hook up an arduino board to the pi 4 it runs alright, doesn't throw the exception. Arduino is recognised as ACM0 not USB0, not sure whether this helps. 

Any ideas?

**Comment by 18554852685** [comment]
hi，i get same problem，do you fix that ? Hope to share it ，thanks。

**Comment by KKimj** [comment]
Hello,

It is correct to start __port of arduino__ with __/dev/ttyACM__. (e.g., /dev/ttyACM0 , /dev/ttyACM1 ... )

c.f
Check running python with __sudo__.
Serial communication requires permission.

**Comment by ApiumJacob** [comment]
> c.f Check running python with **sudo**. Serial communication requires permission.

Maybe add a udev rule to make the port accessible to non root users.
