### ISSUE TITLE
/dev/ttyS0 being filtered out by list_ports on Raspberry Pi

### ISSUE THREAD

**Issue by novirium** [pyserial/pyserial#489]
At least on recent versions of Raspbian (I was testing with Buster), the subsystem for `ttyS0` (the hardware serial port on the Pi) is listed as "platform", and so isn't being returned by `list_ports.comports()` or the `list_ports` tool:

```
pi@raspberry-test:~ $ python3 -m serial.tools.list_ports -v
/dev/ttyAMA0        
    desc: ttyAMA0
    hwid: 3f201000.serial
1 ports found
```

`/dev/ttyS0` is definitely present:
```
pi@raspberry-test:~ $ ls -alh /sys/class/tty/ttyS0/device/subsystem
lrwxrwxrwx 1 root root 0 Feb 14  2019 /sys/class/tty/ttyS0/device/subsystem -> ../../../../bus/platform
```

It's being filtered out by [this line](https://github.com/pyserial/pyserial/blob/3a6ae5a630589a29af8d8bd45616d7aadb2fb3db/serial/tools/list_ports_linux.py#L103) in `list_ports_linux.py` though, which excludes any ports where the subsystem is "platform".

I can see that the code comments this as "hide non-present internal serial ports", but am not exactly sure what this refers to, and it dates back to 2015. [This is the relevant commit](https://github.com/pyserial/pyserial/commit/7d00b8ddd5c26c15782913b3842d35d1c39077d2), which mentions excluding internal ports without hardware IDs.

The `ttyS0` port on the Pi3 and up _is_ an internal port in the main SoC, so list_ports is probably doing what it's intended to (I'm assuming there are non-usable ones on other systems that this is filtering out). If it helps, I did manage to get the data for `ttyS0` PySerial normally looks for:

```
device : /dev/ttyS0
name : ttyS0
description : n/a
hwid : n/a
vid : None
pid : None
serial_number : None
location : None
manufacturer : None
product : None
interface : None
usb_device_path : None
device_path : /sys/devices/platform/soc/3f215040.serial
subsystem : platform
usb_interface_path : None
```

At the moment trying to sort out port autodetect on Raspberry Pis won't work at all - could we either change this exclusion criteria or perhaps add a flag to turn off the filtering?

**Comment by zsquareplusc** [comment]
"hide non-present internal serial ports" was important a few years back when Linux distributions did not use devfs and pre-created 30 or more /dev/ttySx entries... it would be unfortunate to include all those dead entries in a port list. But of course, it would be nice if there is a better exclusion check.

**Comment by e28eta** [comment]
I'd love for this to get addressed. As a newbie trying to use pyserial's `serial.tools.miniterm` and `serial.tools.list_ports`, I spent a *while* churning trying to figure out how to get the TX/RX pins on my Pi 4 working. The tools were *only* showing `/dev/ttyAMA0`, and that wasn't working:

```
$ python3 -m serial.tools.miniterm

--- Available ports:
---  1: /dev/ttyAMA0         'ttyAMA0'
--- Enter port index or full name: 1
--- Miniterm on /dev/ttyAMA0  9600,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
Exception in thread rx:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/serial/tools/miniterm.py", line 445, in reader
    data = self.serial.read(self.serial.in_waiting or 1)
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 467, in in_waiting
    s = fcntl.ioctl(self.fd, TIOCINQ, TIOCM_zero_str)
OSError: [Errno 25] Inappropriate ioctl for device

```

(would this be a reasonable error for pyserial to catch or wrap, in order to provide a hint to users?)

I eventually discovered `/dev/serial` and figured it out, but I trusted pyserial more than I should have.

```
$ ls -l /dev/serial*
lrwxrwxrwx 1 root root 5 Oct  9 15:07 /dev/serial0 -> ttyS0
lrwxrwxrwx 1 root root 7 Oct  9 15:07 /dev/serial1 -> ttyAMA0
```

**Comment by lurch** [comment]
I'd also love to see this fixed somehow :slightly_smiling_face: 

[Thonny](https://thonny.org/) uses pyserial to [list](https://github.com/thonny/thonny/blob/master/thonny/plugins/micropython/__init__.py#L863-L875) serial ports, and this bug means that Thonny only shows `/dev/ttyAMA0` (which is connected to the Bluetooth module), and not `/dev/ttyS0` (which is connected to the GPIO header).
ping @aivarannamaa

**Comment by zsquareplusc** [comment]
it's filtered out by the line checking for "platform" type. however removing this check leads to 30+ non-existing ports reported on the x86 desktop. so just removing that check is no option.

woulnd't mind if anyone finds a better solution ;-)

**Comment by pipiche38** [comment]
Have a similar issue on Fedora distribution on a PI3B+ platform.
While ttyS1 is enabled:
```
 dmesg | grep ttyS1
[    4.361009] 3f215040.serial: ttyS1 at MMIO 0x3f215040 (irq = 53, base_baud = 31250000) is a 16550
[    5.218476] printk: console [ttyS1] enabled
```

python3 -m serial.tools.list_ports doesn't find it !!! while /dev/ttyS1 is up and running and I can access

```
python3 -m serial.tools.list_ports
/dev/ttyUSB0
1 ports found
```

**Comment by tbultel** [comment]
> it's filtered out by the line checking for "platform" type. however removing this check leads to 30+ non-existing ports reported on the x86 desktop. so just removing that check is no option.
> 
> woulnd't mind if anyone finds a better solution ;-)

Hi, why not adding an option for that ? For instance, something like "-p : do not filter out platform devices"
Else, without it, the library is unusable for many (if not all) ARM platforms.

**Comment by vanmierlo** [comment]
Patch #709 fixes the comports() method by an added optional parameter hide_subsystems.
