### ISSUE TITLE
serial.tools.list_ports incompatible with macOS Big Sur v11.0.1?

### ISSUE THREAD

**Issue by K7CTC** [pyserial/pyserial#548]
I have a project that imports and uses serial.tools.list_ports to detect the port a particular device is attached to and connect to it.  It was working beautifully until updating to macOS Big Sur v11.0.1.  I have not modified my code.  I have also tried uninstalling and reinstalling pyserial using pip3.  Now when I run my project I get a traceback:

Traceback (most recent call last):
  File "lostik.py", line 15, in <module>
    import serial.tools.list_ports
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/serial/tools/list_ports_posix.py", line 31, in <module>
    from serial.tools.list_ports_osx import comports
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/serial/tools/list_ports_osx.py", line 32, in <module>
    kIOMasterPortDefault = ctypes.c_void_p.in_dll(iokit, "kIOMasterPortDefault")
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found

I'm not an expert on the subject but recall reading that Big Sur changes the security model of the OS.  For example, the Little Snitch application needed to be reworked by its developers for Big Sur compatibility due to its access to the networking stack.  I'm wondering if there is a limitation to enumerating hardware ports now?

Anyhow, I thought I would bring this to your attention.  Thanks so much for pyserial!!!

**Comment by K7CTC** [comment]
Digging into the pyserial repository source and pull requests... I can see this has already been fixed.  I will see if I can't get the latest pyserial code running and try again.  *was installing pyserial v3.4 via pip.

**Comment by K7CTC** [comment]
Yup... Installed from the latest source and can confirm it is now working again on an Intel MacBook Pro (2018) running macOS Big Sur v11.0.1    AWESOME!!!
