### ISSUE TITLE
Pyserial does not work in Python in Termux on Android, with SerialException

### ISSUE THREAD

**Issue by artisticfox8** [pyserial/pyserial#603]
Here is my python script: 

```
# Importing Libraries
import serial
import time
arduino = serial.Serial(port='COM4', baudrate=115200, timeout=.1)
def write_read(x):
    arduino.write(bytes(x, 'utf-8'))
    time.sleep(0.05)
    data = arduino.readline()
    return data
while True:
    num = input("Enter a number: ") # Taking input from user
    value = write_read(num)
    print(value) # printing the value
```
Here is my arduino script:

```
int x;
void setup() {
 Serial.begin(115200);
 pinMode(LED_BUILTIN, OUTPUT);
 Serial.setTimeout(1);

}
void loop() {
 while (!Serial.available());
 x = Serial.readString().toInt();
 if(x==1){
   digitalWrite(LED_BUILTIN, LOW);
   //Serial.print(x*2);
 }else{
   if(x==2){
     digitalWrite(LED_BUILTIN, HIGH);
   }
 }
 Serial.print(x + 1);
}

```

Here's the python shell code I used to open the python script.
`exec(open("testuju pyserial.py","r").read())`

Here's the error log:

```
Python 3.9.6 (default, Aug  8 2021, 22:47:03)
[Clang 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exec(open("testuju pyserial.py","r"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  TypeError: exec() arg 1 must be a string, bytes or code object
  >>> exec(open("testuju pyserial.py","r").read())Traceback (most recent call last):
    File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/serial/serialposix.py", line 322, in open
        self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
        FileNotFoundError: [Errno 2] No such file or directory: 'COM4'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    File "<string>", line 4, in <module>
      File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/serial/serialutil.py", line 244, in __init__
          self.open()
            File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/serial/serialposix.py", line 325, in open
                raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
                serial.serialutil.SerialException: [Errno 2] could not open port COM4: [Errno 2] No such file or directory: 'COM4'
```
Thanks for your help!

**Comment by mcuee** [comment]
Refer here: https://github.com/pyserial/pyserial/issues/428
There will be no "COM4" under Android.

**Comment by artisticfox8** [comment]
> Refer here: #428
> There will be no "COM4" under Android.

Could there be a  way to emulate with termuxusb or something similar?

**Comment by mcuee** [comment]
> > Refer here: #428
> > There will be no "COM4" under Android.
> 
> Could there be a way to emulate with termuxusb or something similar?

As far as I know that is not possible.

**Comment by mcuee** [comment]
You should use things like this: your paticular board is already supported (Arduino Mega 2560). 
https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java

**Comment by mcuee** [comment]
Or you can also try termux-usb and pyusb.

Ref: termux does not support usb serial: https://github.com/termux/termux-packages/issues/4618
Termux and pyusb: https://github.com/pyusb/pyusb/issues/285

**Comment by artisticfox8** [comment]
> You should use things like this: your paticular board is already supported (Arduino Mega 2560).
> https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/CdcAcmSerialDriver.java

Thank you! How do I integrate it with my python code?

**Comment by mcuee** [comment]
Sorry no idea. Hopefully others can help you with the integration part.

**Comment by mcuee** [comment]
Just test your Arduino code with SimpleUSBTerminal app from Google Play Store and it works fine.

Ref:
Library: https://github.com/mik3y/usb-serial-for-android
App source code (simplified): https://github.com/kai-morich/SimpleUsbTerminal

But no idea how you can get Python to interface with the library.

**Comment by mcuee** [comment]
Refer to #428 You can use python code from here.
https://github.com/jacklinquan/usbserial4a/blob/master/example/usbserial4a_ui_example.py

**Comment by artisticfox8** [comment]
> Refer to #428 You can use python code from here.
> https://github.com/jacklinquan/usbserial4a/blob/master/example/usbserial4a_ui_example.py

Thanks man! It works! Great!

**Comment by kurtmckee** [comment]
@zsquareplusc @dpgeorge Please close this issue. The user's question has been answered.
