### ISSUE TITLE
tools and list ports error..

### ISSUE THREAD

**Issue by Zibri** [pyserial/pyserial#608]
On windows 10.
Python 3.9.6

This works:
`python -m serial.tools.list_ports`

But if I do:
```
>>> import serial
>>> serial.tools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'serial' has no attribute 'tools'

```
and if I do:

```
>>> from serial import tools
>>> serial.tools.list_ports
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'serial.tools' has no attribute 'list_ports'

```
why?!

**Comment by Zibri** [comment]
And also:

```
>>> from serial.tools import list_ports
>>> list
list_ports list(
>>> list_ports()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
>>> serial.tools.li
serial.tools.list_ports         serial.tools.list_ports_windows
serial.tools.list_ports_common
>>> serial.tools.list_ports()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable
>
```

**Comment by pvicol** [comment]
I was able to get the `comports` this way:

```python
from serial.tools import list_ports

ports = list_ports.comports()

for port in ports:
    print(port)
```
and the output:
> /dev/cu.Bluetooth-Incoming-Port - n/a
> /dev/cu.iPhone-WirelessiAPv2 - n/a

**Comment by zsquareplusc** [comment]
see previous response or explicitly `import serial.tools.list_ports` and then call `serial.tools.list_ports.comports()`
