### ISSUE TITLE
UnboundLocalError when using PosixPollSerial with timeout

### ISSUE THREAD

**Issue by Lukanite** [pyserial/pyserial#617]
When using PosixPollSerial, with a timeout, an UnboundLocalError is thrown when the timeout expires without completely fulfilling the read request:
```
>>> ser = serial.serial_for_url("alt:///dev/ttyACM0?class=PosixPollSerial", 115200, timeout=10)
>>> x = ser.read(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/serial/serialposix.py", line 830, in read
    if fd == self.pipe_abort_read_r:
UnboundLocalError: local variable 'fd' referenced before assignment
```

**Comment by codewiz** [comment]
This bug is still present in master.

PR #618 by @Lukanite looks correct to me. Could a maintainer please review it?
