### ISSUE TITLE
Exception in thread rx

### ISSUE THREAD

**Issue by SebDominguez** [pyserial/pyserial#635]
I can see this problem come and go randomly.
Its frustrating since it makes it even harder to pinpoint what's wrong...

```
➜  ~ pio device monitor -p /dev/cu.usbserial-A50285BI -b 115200
--- Available filters and text transformations: colorize, debug, default, direct, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Miniterm on /dev/cu.usbserial-A50285BI  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
Copyright @2019-2020 Heltec Automation.All rights reserved.
Exception in thread rx:
Traceback (most recent call last):
  File "/usr/local/Cellar/platformio/5.2.4/libexec/lib/python3.9/site-packages/serial/serialposix.py", line 575, in read

--- exit ---
    buf = os.read(self.fd, size - len(read))
OSError: [Errno 6] Device not configured

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/platformio/5.2.4/libexec/lib/python3.9/site-packages/serial/tools/miniterm.py", line 499, in reader
    data = self.serial.read(self.serial.in_waiting or 1)
  File "/usr/local/Cellar/platformio/5.2.4/libexec/lib/python3.9/site-packages/serial/serialposix.py", line 581, in read
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: [Errno 6] Device not configured
```

**Comment by SebDominguez** [comment]
The problem was due to a faulty FT232 that somehow had a bad internal 3.3V regulator and wasn't able to power the board properly when some demanding features were activated on the dev board.
