### ISSUE TITLE
Aio - Exception loop when serial device dissapears

### ISSUE THREAD

**Issue by ilfirin-ms** [pyserial/pyserial#68]
When in Protocol serial device dissapears, in my case Bluetooth RFComm died, neverending exception loop started:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
  File "/usr/lib/python3.4/site-packages/serial/aio.py", line 48, in _read_ready
  File "/usr/lib/python3.4/site-packages/serial/serialposix.py", line 505, in read
serial.serialutil.SerialException: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

During handling of the above exception, another exception occurred:

--||--
```

**Comment by zsquareplusc** [comment]
I see.. A fix has been committed that closes the connection in this case. Can you test the current version from git?

**Comment by ilfirin-ms** [comment]
I surely can and .. working perfect. Thank you very much for promt fix, you were so fast, I even hadn't time to create workaround,
