### ISSUE TITLE
Python 3.4 compatibility issue

### ISSUE THREAD

**Issue by michaelso** [pyserial/pyserial#7]
Hi!
Trying to use the PySerial 3.0a which has Py3.4 compatibility. However, it seems there is till issues.

I used it with newest code from master branch of:
https://github.com/faucamp/python-gsmmodem/

DEBUG: write: ATZ
Traceback (most recent call last):
 File "modempool.py", line 180, in <module>
 server.main()
 File "modempool.py", line 139, in main
 modem.connect(PIN)
 File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/python_gsmmodem-0.9-py3.4.egg/gsmmodem/modem.py", line 177, in connect
 File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/python_gsmmodem-0.9-py3.4.egg/gsmmodem/modem.py", line 413, in write

 File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/python_gsmmodem-0.9-py3.4.egg/gsmmodem/serial_comms.py", line 127, in write

 File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyserial-3.0a0-py3.4.egg/serial/serialposix.py", line 513, in write

 File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pyserial-3.0a0-py3.4.egg/serial/serialutil.py", line 57, in to_bytes
TypeError: an integer is required

**Comment by zsquareplusc** [comment]
looking at your code, i see you write (unicode) strings. however the serial port is a stream of bytes.

either you have to apply an encoding yourself when writing (e.g. data.encode('latin1')) or write bytes in the first place (prefix all the strings you are sending and receiving with b, like b"these are bytes"

**Comment by zsquareplusc** [comment]
the latest release should now raise a dedicated exeption if unicode strings are written instead of bytes, which should make it easier to find such an error.
