### ISSUE TITLE
Import of imp breaks with Python 3.12 

### ISSUE THREAD

**Issue by cheri-burnet** [pyserial/pyserial#722]
serial\utilities\\\_init\_.py imports imp.  imp is removed in Python 3.12 so the import of serial no longer works

>>> import serial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\python312\lib\site-packages\serial\\\__init\__.py", line 10, in <module>
    from . import utilities, abc, model, marshal, errors, properties, meta, hooks, test, request
  File "c:\python312\lib\site-packages\serial\utilities\\\__init\__.py", line 5, in <module>
    compatibility.backport()  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\python312\lib\site-packages\serial\utilities\compatibility.py", line 28, in backport
    exec(BACKWARDS_COMPATIBILITY_IMPORTS, frame.f_globals, frame.f_locals)
  File "<string>", line 4, in <module>
  File "c:\python312\lib\site-packages\future\standard_library\\\__init\__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'

**Comment by Knio** [comment]
see https://github.com/PythonCharmers/python-future/issues/625

**Comment by Knio** [comment]
FYI:
this error is from the `serial` library, not `pyserial` (gets me every time)

**Comment by cheri-burnet** [comment]
> FYI: this error is from the `serial` library, not `pyserial` (gets me every time)

You're right, thank you!  My fault, I had both libraries installed and they use the same import statement. I didn't look close enough at the file reference.
