### ISSUE TITLE
aio.py

### ISSUE THREAD

**Issue by guyradford** [pyserial/pyserial#73]
I am running python 3.5.1 on Mac OSX and on my Pi and get the same error...

```
Traceback (most recent call last):
  File "/Users/GuyRadford/Workspace/other/home-thermostat/testing/asyncio.py", line 1, in <module>
    import asyncio
  File "/Users/GuyRadford/Workspace/other/home-thermostat/testing/asyncio.py", line 2, in <module>
    import serial.aio
  File "/Users/GuyRadford/Workspace/other/home-thermostat/venv/lib/python3.5/site-packages/serial/aio.py", line 24, in <module>
    class SerialTransport(asyncio.Transport):
AttributeError: module 'asyncio' has no attribute 'Transport'
```

With a bit of hunting the Transport class lives in a 'asyncio.transports' module, but I cant seem to get this to work... Anyone else having the same issue? anyone found a solution?

Thank you
Guy

**Comment by guyradford** [comment]
I have a feeling this is to do with running python in a virtual environment.... running it without it now works.

**Comment by zsquareplusc** [comment]
The file is there on a Python 3.5 installation i checked, so i guess, as you pointed out, something else went wrong.
