### ISSUE TITLE
pyserial stuck

### ISSUE THREAD

**Issue by jdai** [pyserial/pyserial#736]
>>> ser = serial.Serial(port="COM5", baudrate=115200, bytesize=8, timeout=2, parity=serial.PARITY_NONE, stopbits=serial.STOPBITS_ONE)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python310\lib\site-packages\serial\serialwin32.py", line 33, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\serial\serialutil.py", line 244, in __init__
    self.open()
  File "C:\Program Files\Python310\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM5': PermissionError(13, 'Access is denied.', None, 5)
>>>

1)problem suddenly come when I tried to kill/close other sessions that handles same port. No other programs use COM5.
2)same program line can be used to open other port
3)MobaXterm can be used to open COM5 and response fine. I think it has smart way to reset the port.
4)in python the problem continues.

It is quite obviously that the port is locked somewhere, MobaXterm can ignore it and Pyserial stuck. I can't confirm reproduce steps, basically I use MobaXterm to open a port, then my code to killtask MObaXterm,  ser = serial.Serial(), ser.close() then ser.open(). it works for a few times. People suggest to run ser.close() first incase the port is locked.

**Comment by jdai** [comment]
reproduce steps:
1.run python cmd/interactive mode to open a serial port, but don't close, quit python
2.run python <my.py>, ser = serial.Serial(por then close before open, as in 1) port is not closed. no error.
3.start MobaXterm to open same port, keep it run
4.run python <my.py>, ser = serial.Serial(por , got error. 
5. kill  MobaXterm no help, re-run MobaXterm can still use the port, but python/pyserial cannot use it, same error.

**Comment by jdai** [comment]
windows USB issue, it remains even the process using UART-232 killed. a solution is to kill the user/
