### ISSUE TITLE
"hexlify" encode doesn't work

### ISSUE THREAD

**Issue by periloso** [pyserial/pyserial#87]
Trying to run the hexlify encode doesn't seem to work and an error i thrown:

```
Mac-Pro-di-Alessio:arduino_automac bigalex$ pio -f -c atom serialports monitor --baud 115200 --encoding "hexlify"
Error: __new__() got an unexpected keyword argument '_is_text_encoding'
Mac-Pro-di-Alessio:arduino_automac bigalex$
```

Please let me know if I can make some more tests in case! :)

**Comment by orgkhnargh** [comment]
Just to make it clear. [`pio`](http://platformio.org/) exposes `miniterm` as `pio serialports monitor` command. The error above does not seem to be related to PlatformIO, since executing `miniterm` directly throws the same error:

```
$ python -m serial.tools.miniterm /dev/ttyUSB0 --encoding hexlify
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/path/to/virtualenv/lib/python2.7/site-packages/serial/tools/miniterm.py", line 878, in <module>
    main()
  File "/path/to/virtualenv/lib/python2.7/site-packages/serial/tools/miniterm.py", line 854, in main
    miniterm.set_rx_encoding(args.serial_port_encoding)
  File "/path/to/virtualenv/lib/python2.7/site-packages/serial/tools/miniterm.py", line 365, in set_rx_encoding
    self.rx_decoder = codecs.getincrementaldecoder(encoding)(errors)
  File "/path/to/virtualenv/lib/python2.7/codecs.py", line 968, in getincrementaldecoder
    decoder = lookup(encoding).incrementaldecoder
  File "/path/to/virtualenv/lib/python2.7/site-packages/serial/tools/miniterm.py", line 19, in <lambda>
    codecs.register(lambda c: hexlify_codec.getregentry() if c == 'hexlify' else None)
  File "/path/to/virtualenv/local/lib/python2.7/site-packages/serial/tools/hexlify_codec.py", line 97, in getregentry
    _is_text_encoding=True,
TypeError: __new__() got an unexpected keyword argument '_is_text_encoding'
```
