### ISSUE TITLE
"Failed to set RS485 mode: Inappropriate ioctl for device" exception when trying to set RS485Settings

### ISSUE THREAD

**Issue by SashkaCosmonaut** [pyserial/pyserial#98]
I'm trying to connect the Raspberry Pi 2B with my PC using your wonderful library. This is preparation for another more complicated task. First time I connected them only with serial ports and everything was fine!

But now I have to use RS-485 standard. I have a couple of devices: RS-458 - USB adapter, MAX485 (I tried to use both of them). When I created an object of serial port and set RS485 settings...

```
sender = serial.Serial(
    port = '/dev/ttyUSB1',
    baudrate = 9600,
    parity=serial.PARITY_EVEN,
    stopbits = serial.STOPBITS_ONE,
    bytesize = serial.EIGHTBITS,
    timeout = 3
)

sender.rs485_mode = serial.rs485.RS485Settings(delay_before_tx=1, delay_before_rx=1)
```

... I've got the next exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pyserial-3.1a0-py3.4.egg/serial/serialposix.py", line 133, in _set_rs485_mode
    fcntl.ioctl(self.fd, TIOCGRS485, buf)
OSError: [Errno 25] Inappropriate ioctl for device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    sender.rs485_mode = serial.rs485.RS485Settings(delay_before_tx=1, delay_before_rx=1)
  File "/usr/local/lib/python3.4/dist-packages/pyserial-3.1a0-py3.4.egg/serial/serialutil.py", line 422, in rs485_mode
    self._reconfigure_port()
  File "/usr/local/lib/python3.4/dist-packages/pyserial-3.1a0-py3.4.egg/serial/serialposix.py", line 450, in _reconfigure_port
    self._set_rs485_mode(self._rs485_mode)
  File "/usr/local/lib/python3.4/dist-packages/pyserial-3.1a0-py3.4.egg/serial/serialposix.py", line 154, in _set_rs485_mode
    raise ValueError('Failed to set RS485 mode: {}'.format(e))
ValueError: Failed to set RS485 mode: [Errno 25] Inappropriate ioctl for device 
```

Can you help me please or at least give me an advice? Is this problem connected with your library or this is problem of a device or Raspberry PI?

**Comment by zsquareplusc** [comment]
- Are you testing a fresh checkout where #96 is already committed?
- Not many adapters seem to support RS485, i think ido not have a single one.
- the `serial.rs485` module has a [class](https://pyserial.readthedocs.org/en/latest/pyserial_api.html#serial.rs485.RS485) where RTS is operated "manually" in the `write` method. This may or may not work...

**Comment by SashkaCosmonaut** [comment]
Thank you for the reply! Answer your questioins:

1) Yes, I cloned the repository with all last changes.

3) I created an object of `serial.rs485.RS485` and set `RS485Settings` and there wasn't any exception, thats good! But I couldn't receive any message. Nevertheless, I am newbie in serial ports and RS-485, so I'm not sure that I clearly understand such parameters as delay_before_tx/rx, RTS/CTS, DSR/DTR etc. Maybe I have just set it up wrong for my devices and such case can't be a good test.

2) I googled a lot and found some solutions where people used more complicated devices. For example Russian ones: 'Меркурий 221 USB to CAN/RS-232/RS485' or 'Сапфир USB to RS232-RS485/422' (I thing there are a lot of international analogs). Such devices take care of all the low-level settings of RS-485 so you can use them like normal serial port. Luckily I have one of these (Сапфир). I used simple `Serial` class of your library and finally everything works!

However, I don't think it is good solution because the question is opened for simple devices like RS-458 - USB adapter, MAX485, HL-340 with RS-485 converter etc.

Anyway, thank you very much for your help!

**Comment by cristi-badila** [comment]
Same thing happens to me when trying to use the library with a Raspberry 2 v1.1. I can enable default rts/cts for the serial port from the raspbian terminal using `stty -F /dev/ttyAMA0 crtscts` and can see the RTS signal being triggered when transmitting data from the terminal using something like `echo Test > /dev/ttyAMA0`. (to be able to access the RTS signal on GPIO 17 an alternate function mode needs to be enabled for it more info [here](https://github.com/mholling/rpirtscts)) To me it seems like the Raspberry board/driver support hardware flow control but something goes wrong when trying to enable it from pymodbus, thus the error mentioned above. Does anybody have any idea on how I could try to debug/fix this issue any more?

**Comment by SashkaCosmonaut** [comment]
@cristi-badila I asked the similar question on [Raspberry Pi Stackexchange](http://raspberrypi.stackexchange.com/questions/44454/cant-send-data-from-the-raspberry-pi-via-rs485-and-serial-port). Maybe it will be helpful to you.

**Comment by Pyponou** [comment]
I am currently having the same issue :

`from pymodbus.client.sync import ModbusSerialClient as ModbusClient
import serial.rs485

client = ModbusClient(method='rtu', port='/dev/ttyAMA1', timeout=1, baudrate=9600)
client.connect()
rs485_mode = serial.rs485.RS485Settings(delay_before_tx = 0, delay_before_rx = 0, rts_level_for_tx=False, rts_level_for_rx=True, loopback=True)
client.socket.rs485_mode = rs485_mode`

But It triggers this exception :

`  File "/home/app/env/lib/python3.7/site-packages/serial/serialutil.py", line 500, in rs485_mode
    self._reconfigure_port()
  File "/home/app/env/lib/python3.7/site-packages/serial/serialposix.py", line 527, in _reconfigure_port
    self._set_rs485_mode(self._rs485_mode)
  File "/home/app/env/lib/python3.7/site-packages/serial/serialposix.py", line 190, in _set_rs485_mode
    raise ValueError('Failed to set RS485 mode: {}'.format(e))
ValueError: Failed to set RS485 mode: [Errno 25] Inappropriate ioctl for device
` 


Pyserial version 3.5 on a rapsberry pi 4

Did you find a solution ?

**Comment by SashkaCosmonaut** [comment]
@Pyponou if I remember correctly my problem was in my RS-458 - USB adapter which didn't support required port parameters (parity, stopbits, bytesize). I could set up other values for these parameters on both sides (PC and Raspberry), may be it will help you. But for me it was crucial to keep them like that for other equipment I used with a Raspberry, where I could't change them.

**Comment by SashkaCosmonaut** [comment]
Sorry, accidentally closed this issue. Misclicked.

@Pyponou if I remember correctly my problem was in my RS-458 - USB adapter which didn't support required port parameters (parity, stopbits, bytesize). I could set up other values for these parameters on both sides (PC and Raspberry), may be it will help you. But for me it was crucial to keep them like that for other equipment I used with a Raspberry, where I could't change them.

**Comment by SashkaCosmonaut** [comment]
Sorry, accidentally closed this issue. Misclicked.

@Pyponou if I remember correctly my problem was in my RS-458 - USB adapter which didn't support required port parameters (parity, stopbits, bytesize). I could set up other values for these parameters on both sides (PC and Raspberry), may be it will help you. But for me it was crucial to keep them like that for other equipment I used with a Raspberry, where I could't change them.

**Comment by Pyponou** [comment]
@SashkaCosmonaut Thank you for your quick answer
In fact, the problem seems coming from pymodbus that creates a serial.Serial instead of serial.rs485.RS485 when creating a ModbusSerialClient :/
